[versions]
agp = "8.10.1"
firebaseBom = "33.16.0"
kotlin = "2.2.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2025.07.00"
navigationCompose = "2.9.2"
navigationRuntimeAndroid = "2.9.2"
firebaseAuthKtx = "23.2.1"
androidDatastorePreferences = "1.1.1"
androidSecurityCrypto = "1.1.0-alpha06"
coroutines = "1.8.1"
kermit = "2.0.4"
kermit-core = "2.0.4"
roomRuntime = "2.7.2"
touchlabSettings= "1.3.0"

[bundles]

touchlab-common = [
    "touchlab-kermit",
    "touchlab-settings",
    "touchlab-settings-coroutines",
    "tochlab-settings-observable"
]


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-runtime-android = { group = "androidx.navigation", name = "navigation-runtime-android", version.ref = "navigationRuntimeAndroid" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }

#datastore is used in tochlab settings as well
android-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidDatastorePreferences" }
android-security-crypto = { module = "androidx.security:security-crypto", version.ref = "androidSecurityCrypto" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

#touchlab-libraries
touchlab-kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
touchlab-core = { module = "co.touchlab:kermit-core", version.ref = "kermit-core" }
touchlab-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "touchlabSettings" }
touchlab-settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "touchlabSettings" }
tochlab-settings-observable = { module = "com.russhwolf:multiplatform-settings-make-observable", version.ref = "touchlabSettings"}
touchlab-settings-test = { module = "com.russhwolf:multiplatform-settings-test", version.ref = "touchlabSettings" }
touchlab-settings-datastore = { module = "com.russhwolf:multiplatform-settings-datastore", version.ref = "touchlabSettings"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
